#!/bin/bash
set -euo pipefail

# =============================================================================
# Cloudflare Foundation - Complete Infrastructure Setup
# =============================================================================
# This script creates all required Cloudflare resources:
# - 2 D1 databases (foundation-primary + planning-primary)
# - 3 KV namespaces
# - 1 R2 bucket
# - 4 queues
# =============================================================================

echo "=== Cloudflare Foundation v2.5 — Infrastructure Setup ==="
echo ""
echo "This script will create all required Cloudflare resources."
echo "Make sure you are logged in: wrangler login"
echo ""

# Check if wrangler is available
if ! command -v wrangler &> /dev/null; then
    echo "ERROR: wrangler CLI not found. Install with: npm install -g wrangler"
    exit 1
fi

# Output file for IDs
OUTPUT_FILE=".env.local"
echo "# Generated by setup-all.sh on $(date)" > $OUTPUT_FILE
echo "# Copy these values to your wrangler.jsonc files" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# =============================================================================
# D1 Databases
# =============================================================================
echo "Creating D1 databases..."

echo "  -> foundation-primary (main database)..."
FOUNDATION_DB=$(wrangler d1 create foundation-primary 2>&1 | grep "database_id" | awk -F'"' '{print $2}')
if [ -n "$FOUNDATION_DB" ]; then
    echo "D1_FOUNDATION_ID=$FOUNDATION_DB" >> $OUTPUT_FILE
    echo "     Created: $FOUNDATION_DB"
else
    echo "     WARNING: Could not parse database ID. Check output manually."
    wrangler d1 create foundation-primary || echo "     Database may already exist."
fi

echo "  -> planning-primary (planning machine database)..."
PLANNING_DB=$(wrangler d1 create planning-primary 2>&1 | grep "database_id" | awk -F'"' '{print $2}')
if [ -n "$PLANNING_DB" ]; then
    echo "D1_PLANNING_ID=$PLANNING_DB" >> $OUTPUT_FILE
    echo "     Created: $PLANNING_DB"
else
    echo "     WARNING: Could not parse database ID. Check output manually."
    wrangler d1 create planning-primary || echo "     Database may already exist."
fi

# =============================================================================
# KV Namespaces
# =============================================================================
echo ""
echo "Creating KV namespaces..."

echo "  -> RATE_LIMIT_KV..."
RATE_LIMIT_KV=$(wrangler kv:namespace create RATE_LIMIT_KV 2>&1 | grep "id = " | awk -F'"' '{print $2}')
if [ -n "$RATE_LIMIT_KV" ]; then
    echo "KV_RATE_LIMIT_ID=$RATE_LIMIT_KV" >> $OUTPUT_FILE
    echo "     Created: $RATE_LIMIT_KV"
else
    echo "     WARNING: Could not parse namespace ID."
    wrangler kv:namespace create RATE_LIMIT_KV || echo "     Namespace may already exist."
fi

echo "  -> SESSION_KV..."
SESSION_KV=$(wrangler kv:namespace create SESSION_KV 2>&1 | grep "id = " | awk -F'"' '{print $2}')
if [ -n "$SESSION_KV" ]; then
    echo "KV_SESSION_ID=$SESSION_KV" >> $OUTPUT_FILE
    echo "     Created: $SESSION_KV"
else
    echo "     WARNING: Could not parse namespace ID."
    wrangler kv:namespace create SESSION_KV || echo "     Namespace may already exist."
fi

echo "  -> CACHE_KV..."
CACHE_KV=$(wrangler kv:namespace create CACHE_KV 2>&1 | grep "id = " | awk -F'"' '{print $2}')
if [ -n "$CACHE_KV" ]; then
    echo "KV_CACHE_ID=$CACHE_KV" >> $OUTPUT_FILE
    echo "     Created: $CACHE_KV"
else
    echo "     WARNING: Could not parse namespace ID."
    wrangler kv:namespace create CACHE_KV || echo "     Namespace may already exist."
fi

# =============================================================================
# R2 Buckets
# =============================================================================
echo ""
echo "Creating R2 buckets..."

echo "  -> foundation-files..."
wrangler r2 bucket create foundation-files 2>/dev/null || echo "     Bucket may already exist."
echo "R2_FOUNDATION_BUCKET=foundation-files" >> $OUTPUT_FILE

echo "  -> planning-files..."
wrangler r2 bucket create planning-files 2>/dev/null || echo "     Bucket may already exist."
echo "R2_PLANNING_BUCKET=planning-files" >> $OUTPUT_FILE

# =============================================================================
# Queues
# =============================================================================
echo ""
echo "Creating queues..."

for queue in foundation-audit foundation-notifications foundation-analytics foundation-webhooks; do
    echo "  -> $queue..."
    wrangler queues create $queue 2>/dev/null || echo "     Queue may already exist."
done

echo "QUEUES_CREATED=foundation-audit,foundation-notifications,foundation-analytics,foundation-webhooks" >> $OUTPUT_FILE

# =============================================================================
# Summary
# =============================================================================
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Resource IDs have been saved to: $OUTPUT_FILE"
echo ""
echo "NEXT STEPS:"
echo "1. Copy the IDs from $OUTPUT_FILE to your wrangler.jsonc files"
echo "2. Set required secrets:"
echo "   wrangler secret put CONTEXT_SIGNING_KEY"
echo "   wrangler secret put TURNSTILE_SECRET"
echo "3. Run database migrations:"
echo "   cd services/gateway && wrangler d1 migrations apply foundation-primary --remote"
echo "   cd services/planning-machine && wrangler d1 migrations apply planning-primary --remote"
echo "4. Validate configuration:"
echo "   ./scripts/validate-config.sh"
echo "5. Deploy all services:"
echo "   ./scripts/deploy-all.sh"
echo ""
cat $OUTPUT_FILE
